name: Auto-merge squash
on: pull_request_target
    
permissions:
  contents: read
  pull-requests: read
    
jobs:
  auto-merge:
    permissions:
      contents: write
      pull-requests: write
    uses: greenbone/workflows/.github/workflows/auto-merge.yml@main
    secrets: inherit
