name: Deploy on PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pontos/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: greenbone/actions/poetry@v3
        with:
          python-version: "3.10"
          install-dependencies: "false"
      - name: Build
        run: |
          poetry build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
